#!/usr/bin/env bash
set -euo pipefail

# download-deps.sh
# Downloads all 156 npm package tarballs for offline install.
# Run this on a machine with network access to registry.npmjs.org

DEST="vendor/tarballs"
mkdir -p "$DEST"

echo "Downloading @babel__runtime__runtime-7.29.2.tgz..."
curl -sL -o "$DEST/@babel__runtime__runtime-7.29.2.tgz" "https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.2.tgz"
echo "Downloading @dimforge__rapier3d-compat__rapier3d-compat-0.12.0.tgz..."
curl -sL -o "$DEST/@dimforge__rapier3d-compat__rapier3d-compat-0.12.0.tgz" "https://registry.npmjs.org/@dimforge/rapier3d-compat/-/rapier3d-compat-0.12.0.tgz"
echo "Downloading @emnapi__core__core-1.9.1.tgz..."
curl -sL -o "$DEST/@emnapi__core__core-1.9.1.tgz" "https://registry.npmjs.org/@emnapi/core/-/core-1.9.1.tgz"
echo "Downloading @emnapi__runtime__runtime-1.9.1.tgz..."
curl -sL -o "$DEST/@emnapi__runtime__runtime-1.9.1.tgz" "https://registry.npmjs.org/@emnapi/runtime/-/runtime-1.9.1.tgz"
echo "Downloading @emnapi__wasi-threads__wasi-threads-1.2.0.tgz..."
curl -sL -o "$DEST/@emnapi__wasi-threads__wasi-threads-1.2.0.tgz" "https://registry.npmjs.org/@emnapi/wasi-threads/-/wasi-threads-1.2.0.tgz"
echo "Downloading @jridgewell__gen-mapping__gen-mapping-0.3.13.tgz..."
curl -sL -o "$DEST/@jridgewell__gen-mapping__gen-mapping-0.3.13.tgz" "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz"
echo "Downloading @jridgewell__remapping__remapping-2.3.5.tgz..."
curl -sL -o "$DEST/@jridgewell__remapping__remapping-2.3.5.tgz" "https://registry.npmjs.org/@jridgewell/remapping/-/remapping-2.3.5.tgz"
echo "Downloading @jridgewell__resolve-uri__resolve-uri-3.1.2.tgz..."
curl -sL -o "$DEST/@jridgewell__resolve-uri__resolve-uri-3.1.2.tgz" "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz"
echo "Downloading @jridgewell__sourcemap-codec__sourcemap-codec-1.5.5.tgz..."
curl -sL -o "$DEST/@jridgewell__sourcemap-codec__sourcemap-codec-1.5.5.tgz" "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz"
echo "Downloading @jridgewell__trace-mapping__trace-mapping-0.3.31.tgz..."
curl -sL -o "$DEST/@jridgewell__trace-mapping__trace-mapping-0.3.31.tgz" "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz"
echo "Downloading @mediapipe__tasks-vision__tasks-vision-0.10.17.tgz..."
curl -sL -o "$DEST/@mediapipe__tasks-vision__tasks-vision-0.10.17.tgz" "https://registry.npmjs.org/@mediapipe/tasks-vision/-/tasks-vision-0.10.17.tgz"
echo "Downloading @monogrid__gainmap-js__gainmap-js-3.4.0.tgz..."
curl -sL -o "$DEST/@monogrid__gainmap-js__gainmap-js-3.4.0.tgz" "https://registry.npmjs.org/@monogrid/gainmap-js/-/gainmap-js-3.4.0.tgz"
echo "Downloading @napi-rs__wasm-runtime__wasm-runtime-1.1.2.tgz..."
curl -sL -o "$DEST/@napi-rs__wasm-runtime__wasm-runtime-1.1.2.tgz" "https://registry.npmjs.org/@napi-rs/wasm-runtime/-/wasm-runtime-1.1.2.tgz"
echo "Downloading @oxc-project__types__types-0.122.0.tgz..."
curl -sL -o "$DEST/@oxc-project__types__types-0.122.0.tgz" "https://registry.npmjs.org/@oxc-project/types/-/types-0.122.0.tgz"
echo "Downloading @react-three__drei__drei-10.7.7.tgz..."
curl -sL -o "$DEST/@react-three__drei__drei-10.7.7.tgz" "https://registry.npmjs.org/@react-three/drei/-/drei-10.7.7.tgz"
echo "Downloading @react-three__fiber__fiber-9.5.0.tgz..."
curl -sL -o "$DEST/@react-three__fiber__fiber-9.5.0.tgz" "https://registry.npmjs.org/@react-three/fiber/-/fiber-9.5.0.tgz"
echo "Downloading @rolldown__binding-android-arm64__binding-android-arm64-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-android-arm64__binding-android-arm64-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-android-arm64/-/binding-android-arm64-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-darwin-arm64__binding-darwin-arm64-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-darwin-arm64__binding-darwin-arm64-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-darwin-arm64/-/binding-darwin-arm64-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-darwin-x64__binding-darwin-x64-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-darwin-x64__binding-darwin-x64-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-darwin-x64/-/binding-darwin-x64-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-freebsd-x64__binding-freebsd-x64-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-freebsd-x64__binding-freebsd-x64-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-freebsd-x64/-/binding-freebsd-x64-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-arm-gnueabihf__binding-linux-arm-gnueabihf-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-arm-gnueabihf__binding-linux-arm-gnueabihf-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-arm-gnueabihf/-/binding-linux-arm-gnueabihf-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-arm64-gnu__binding-linux-arm64-gnu-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-arm64-gnu__binding-linux-arm64-gnu-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-arm64-gnu/-/binding-linux-arm64-gnu-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-arm64-musl__binding-linux-arm64-musl-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-arm64-musl__binding-linux-arm64-musl-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-arm64-musl/-/binding-linux-arm64-musl-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-ppc64-gnu__binding-linux-ppc64-gnu-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-ppc64-gnu__binding-linux-ppc64-gnu-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-ppc64-gnu/-/binding-linux-ppc64-gnu-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-s390x-gnu__binding-linux-s390x-gnu-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-s390x-gnu__binding-linux-s390x-gnu-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-s390x-gnu/-/binding-linux-s390x-gnu-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-x64-gnu__binding-linux-x64-gnu-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-x64-gnu__binding-linux-x64-gnu-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-x64-gnu/-/binding-linux-x64-gnu-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-linux-x64-musl__binding-linux-x64-musl-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-linux-x64-musl__binding-linux-x64-musl-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-linux-x64-musl/-/binding-linux-x64-musl-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-openharmony-arm64__binding-openharmony-arm64-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-openharmony-arm64__binding-openharmony-arm64-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-openharmony-arm64/-/binding-openharmony-arm64-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-wasm32-wasi__binding-wasm32-wasi-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-wasm32-wasi__binding-wasm32-wasi-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-wasm32-wasi/-/binding-wasm32-wasi-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-win32-arm64-msvc__binding-win32-arm64-msvc-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-win32-arm64-msvc__binding-win32-arm64-msvc-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-win32-arm64-msvc/-/binding-win32-arm64-msvc-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__binding-win32-x64-msvc__binding-win32-x64-msvc-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__binding-win32-x64-msvc__binding-win32-x64-msvc-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/binding-win32-x64-msvc/-/binding-win32-x64-msvc-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__pluginutils__pluginutils-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/@rolldown__pluginutils__pluginutils-1.0.0-rc.12.tgz" "https://registry.npmjs.org/@rolldown/pluginutils/-/pluginutils-1.0.0-rc.12.tgz"
echo "Downloading @rolldown__pluginutils__pluginutils-1.0.0-rc.7.tgz..."
curl -sL -o "$DEST/@rolldown__pluginutils__pluginutils-1.0.0-rc.7.tgz" "https://registry.npmjs.org/@rolldown/pluginutils/-/pluginutils-1.0.0-rc.7.tgz"
echo "Downloading @tailwindcss__node__node-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__node__node-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/node/-/node-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-android-arm64__oxide-android-arm64-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-android-arm64__oxide-android-arm64-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-android-arm64/-/oxide-android-arm64-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-darwin-arm64__oxide-darwin-arm64-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-darwin-arm64__oxide-darwin-arm64-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-darwin-arm64/-/oxide-darwin-arm64-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-darwin-x64__oxide-darwin-x64-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-darwin-x64__oxide-darwin-x64-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-darwin-x64/-/oxide-darwin-x64-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-freebsd-x64__oxide-freebsd-x64-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-freebsd-x64__oxide-freebsd-x64-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-freebsd-x64/-/oxide-freebsd-x64-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-linux-arm-gnueabihf__oxide-linux-arm-gnueabihf-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-linux-arm-gnueabihf__oxide-linux-arm-gnueabihf-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm-gnueabihf/-/oxide-linux-arm-gnueabihf-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-linux-arm64-gnu__oxide-linux-arm64-gnu-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-linux-arm64-gnu__oxide-linux-arm64-gnu-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm64-gnu/-/oxide-linux-arm64-gnu-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-linux-arm64-musl__oxide-linux-arm64-musl-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-linux-arm64-musl__oxide-linux-arm64-musl-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm64-musl/-/oxide-linux-arm64-musl-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-linux-x64-gnu__oxide-linux-x64-gnu-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-linux-x64-gnu__oxide-linux-x64-gnu-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-gnu/-/oxide-linux-x64-gnu-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-linux-x64-musl__oxide-linux-x64-musl-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-linux-x64-musl__oxide-linux-x64-musl-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-musl/-/oxide-linux-x64-musl-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-wasm32-wasi__oxide-wasm32-wasi-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-wasm32-wasi__oxide-wasm32-wasi-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-wasm32-wasi/-/oxide-wasm32-wasi-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-win32-arm64-msvc__oxide-win32-arm64-msvc-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-win32-arm64-msvc__oxide-win32-arm64-msvc-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-win32-arm64-msvc/-/oxide-win32-arm64-msvc-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide-win32-x64-msvc__oxide-win32-x64-msvc-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide-win32-x64-msvc__oxide-win32-x64-msvc-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide-win32-x64-msvc/-/oxide-win32-x64-msvc-4.2.2.tgz"
echo "Downloading @tailwindcss__oxide__oxide-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__oxide__oxide-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/oxide/-/oxide-4.2.2.tgz"
echo "Downloading @tailwindcss__vite__vite-4.2.2.tgz..."
curl -sL -o "$DEST/@tailwindcss__vite__vite-4.2.2.tgz" "https://registry.npmjs.org/@tailwindcss/vite/-/vite-4.2.2.tgz"
echo "Downloading @tauri-apps__api__api-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__api__api-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/api/-/api-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-darwin-arm64__cli-darwin-arm64-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-darwin-arm64__cli-darwin-arm64-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-darwin-arm64/-/cli-darwin-arm64-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-darwin-x64__cli-darwin-x64-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-darwin-x64__cli-darwin-x64-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-darwin-x64/-/cli-darwin-x64-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-arm-gnueabihf__cli-linux-arm-gnueabihf-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-arm-gnueabihf__cli-linux-arm-gnueabihf-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-arm-gnueabihf/-/cli-linux-arm-gnueabihf-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-arm64-gnu__cli-linux-arm64-gnu-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-arm64-gnu__cli-linux-arm64-gnu-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-arm64-gnu/-/cli-linux-arm64-gnu-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-arm64-musl__cli-linux-arm64-musl-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-arm64-musl__cli-linux-arm64-musl-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-arm64-musl/-/cli-linux-arm64-musl-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-riscv64-gnu__cli-linux-riscv64-gnu-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-riscv64-gnu__cli-linux-riscv64-gnu-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-riscv64-gnu/-/cli-linux-riscv64-gnu-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-x64-gnu__cli-linux-x64-gnu-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-x64-gnu__cli-linux-x64-gnu-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-x64-gnu/-/cli-linux-x64-gnu-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-linux-x64-musl__cli-linux-x64-musl-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-linux-x64-musl__cli-linux-x64-musl-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-linux-x64-musl/-/cli-linux-x64-musl-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-win32-arm64-msvc__cli-win32-arm64-msvc-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-win32-arm64-msvc__cli-win32-arm64-msvc-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-win32-arm64-msvc/-/cli-win32-arm64-msvc-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-win32-ia32-msvc__cli-win32-ia32-msvc-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-win32-ia32-msvc__cli-win32-ia32-msvc-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-win32-ia32-msvc/-/cli-win32-ia32-msvc-2.10.1.tgz"
echo "Downloading @tauri-apps__cli-win32-x64-msvc__cli-win32-x64-msvc-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli-win32-x64-msvc__cli-win32-x64-msvc-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli-win32-x64-msvc/-/cli-win32-x64-msvc-2.10.1.tgz"
echo "Downloading @tauri-apps__cli__cli-2.10.1.tgz..."
curl -sL -o "$DEST/@tauri-apps__cli__cli-2.10.1.tgz" "https://registry.npmjs.org/@tauri-apps/cli/-/cli-2.10.1.tgz"
echo "Downloading @tweenjs__tween.js__tween.js-23.1.3.tgz..."
curl -sL -o "$DEST/@tweenjs__tween.js__tween.js-23.1.3.tgz" "https://registry.npmjs.org/@tweenjs/tween.js/-/tween.js-23.1.3.tgz"
echo "Downloading @tybys__wasm-util__wasm-util-0.10.1.tgz..."
curl -sL -o "$DEST/@tybys__wasm-util__wasm-util-0.10.1.tgz" "https://registry.npmjs.org/@tybys/wasm-util/-/wasm-util-0.10.1.tgz"
echo "Downloading @types__draco3d__draco3d-1.4.10.tgz..."
curl -sL -o "$DEST/@types__draco3d__draco3d-1.4.10.tgz" "https://registry.npmjs.org/@types/draco3d/-/draco3d-1.4.10.tgz"
echo "Downloading @types__offscreencanvas__offscreencanvas-2019.7.3.tgz..."
curl -sL -o "$DEST/@types__offscreencanvas__offscreencanvas-2019.7.3.tgz" "https://registry.npmjs.org/@types/offscreencanvas/-/offscreencanvas-2019.7.3.tgz"
echo "Downloading @types__react-reconciler__react-reconciler-0.28.9.tgz..."
curl -sL -o "$DEST/@types__react-reconciler__react-reconciler-0.28.9.tgz" "https://registry.npmjs.org/@types/react-reconciler/-/react-reconciler-0.28.9.tgz"
echo "Downloading @types__stats.js__stats.js-0.17.4.tgz..."
curl -sL -o "$DEST/@types__stats.js__stats.js-0.17.4.tgz" "https://registry.npmjs.org/@types/stats.js/-/stats.js-0.17.4.tgz"
echo "Downloading @types__three__three-0.183.1.tgz..."
curl -sL -o "$DEST/@types__three__three-0.183.1.tgz" "https://registry.npmjs.org/@types/three/-/three-0.183.1.tgz"
echo "Downloading @types__webxr__webxr-0.5.24.tgz..."
curl -sL -o "$DEST/@types__webxr__webxr-0.5.24.tgz" "https://registry.npmjs.org/@types/webxr/-/webxr-0.5.24.tgz"
echo "Downloading @use-gesture__core__core-10.3.1.tgz..."
curl -sL -o "$DEST/@use-gesture__core__core-10.3.1.tgz" "https://registry.npmjs.org/@use-gesture/core/-/core-10.3.1.tgz"
echo "Downloading @use-gesture__react__react-10.3.1.tgz..."
curl -sL -o "$DEST/@use-gesture__react__react-10.3.1.tgz" "https://registry.npmjs.org/@use-gesture/react/-/react-10.3.1.tgz"
echo "Downloading @vitejs__plugin-react__plugin-react-6.0.1.tgz..."
curl -sL -o "$DEST/@vitejs__plugin-react__plugin-react-6.0.1.tgz" "https://registry.npmjs.org/@vitejs/plugin-react/-/plugin-react-6.0.1.tgz"
echo "Downloading @webgpu__types__types-0.1.69.tgz..."
curl -sL -o "$DEST/@webgpu__types__types-0.1.69.tgz" "https://registry.npmjs.org/@webgpu/types/-/types-0.1.69.tgz"
echo "Downloading base64-js__base64-js-1.5.1.tgz..."
curl -sL -o "$DEST/base64-js__base64-js-1.5.1.tgz" "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz"
echo "Downloading bidi-js__bidi-js-1.0.3.tgz..."
curl -sL -o "$DEST/bidi-js__bidi-js-1.0.3.tgz" "https://registry.npmjs.org/bidi-js/-/bidi-js-1.0.3.tgz"
echo "Downloading buffer__buffer-6.0.3.tgz..."
curl -sL -o "$DEST/buffer__buffer-6.0.3.tgz" "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz"
echo "Downloading camera-controls__camera-controls-3.1.2.tgz..."
curl -sL -o "$DEST/camera-controls__camera-controls-3.1.2.tgz" "https://registry.npmjs.org/camera-controls/-/camera-controls-3.1.2.tgz"
echo "Downloading cross-env__cross-env-7.0.3.tgz..."
curl -sL -o "$DEST/cross-env__cross-env-7.0.3.tgz" "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz"
echo "Downloading cross-spawn__cross-spawn-7.0.6.tgz..."
curl -sL -o "$DEST/cross-spawn__cross-spawn-7.0.6.tgz" "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz"
echo "Downloading detect-gpu__detect-gpu-5.0.70.tgz..."
curl -sL -o "$DEST/detect-gpu__detect-gpu-5.0.70.tgz" "https://registry.npmjs.org/detect-gpu/-/detect-gpu-5.0.70.tgz"
echo "Downloading detect-libc__detect-libc-2.1.2.tgz..."
curl -sL -o "$DEST/detect-libc__detect-libc-2.1.2.tgz" "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz"
echo "Downloading draco3d__draco3d-1.5.7.tgz..."
curl -sL -o "$DEST/draco3d__draco3d-1.5.7.tgz" "https://registry.npmjs.org/draco3d/-/draco3d-1.5.7.tgz"
echo "Downloading enhanced-resolve__enhanced-resolve-5.20.1.tgz..."
curl -sL -o "$DEST/enhanced-resolve__enhanced-resolve-5.20.1.tgz" "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.20.1.tgz"
echo "Downloading fdir__fdir-6.5.0.tgz..."
curl -sL -o "$DEST/fdir__fdir-6.5.0.tgz" "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz"
echo "Downloading fflate__fflate-0.6.10.tgz..."
curl -sL -o "$DEST/fflate__fflate-0.6.10.tgz" "https://registry.npmjs.org/fflate/-/fflate-0.6.10.tgz"
echo "Downloading fflate__fflate-0.8.2.tgz..."
curl -sL -o "$DEST/fflate__fflate-0.8.2.tgz" "https://registry.npmjs.org/fflate/-/fflate-0.8.2.tgz"
echo "Downloading fsevents__fsevents-2.3.3.tgz..."
curl -sL -o "$DEST/fsevents__fsevents-2.3.3.tgz" "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz"
echo "Downloading glsl-noise__glsl-noise-0.0.0.tgz..."
curl -sL -o "$DEST/glsl-noise__glsl-noise-0.0.0.tgz" "https://registry.npmjs.org/glsl-noise/-/glsl-noise-0.0.0.tgz"
echo "Downloading graceful-fs__graceful-fs-4.2.11.tgz..."
curl -sL -o "$DEST/graceful-fs__graceful-fs-4.2.11.tgz" "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz"
echo "Downloading hls.js__hls.js-1.6.15.tgz..."
curl -sL -o "$DEST/hls.js__hls.js-1.6.15.tgz" "https://registry.npmjs.org/hls.js/-/hls.js-1.6.15.tgz"
echo "Downloading ieee754__ieee754-1.2.1.tgz..."
curl -sL -o "$DEST/ieee754__ieee754-1.2.1.tgz" "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz"
echo "Downloading immediate__immediate-3.0.6.tgz..."
curl -sL -o "$DEST/immediate__immediate-3.0.6.tgz" "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz"
echo "Downloading is-promise__is-promise-2.2.2.tgz..."
curl -sL -o "$DEST/is-promise__is-promise-2.2.2.tgz" "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz"
echo "Downloading isexe__isexe-2.0.0.tgz..."
curl -sL -o "$DEST/isexe__isexe-2.0.0.tgz" "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz"
echo "Downloading its-fine__its-fine-2.0.0.tgz..."
curl -sL -o "$DEST/its-fine__its-fine-2.0.0.tgz" "https://registry.npmjs.org/its-fine/-/its-fine-2.0.0.tgz"
echo "Downloading jiti__jiti-2.6.1.tgz..."
curl -sL -o "$DEST/jiti__jiti-2.6.1.tgz" "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz"
echo "Downloading js-tokens__js-tokens-4.0.0.tgz..."
curl -sL -o "$DEST/js-tokens__js-tokens-4.0.0.tgz" "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz"
echo "Downloading lie__lie-3.3.0.tgz..."
curl -sL -o "$DEST/lie__lie-3.3.0.tgz" "https://registry.npmjs.org/lie/-/lie-3.3.0.tgz"
echo "Downloading lightningcss-android-arm64__lightningcss-android-arm64-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-android-arm64__lightningcss-android-arm64-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-android-arm64/-/lightningcss-android-arm64-1.32.0.tgz"
echo "Downloading lightningcss-darwin-arm64__lightningcss-darwin-arm64-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-darwin-arm64__lightningcss-darwin-arm64-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.32.0.tgz"
echo "Downloading lightningcss-darwin-x64__lightningcss-darwin-x64-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-darwin-x64__lightningcss-darwin-x64-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.32.0.tgz"
echo "Downloading lightningcss-freebsd-x64__lightningcss-freebsd-x64-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-freebsd-x64__lightningcss-freebsd-x64-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.32.0.tgz"
echo "Downloading lightningcss-linux-arm-gnueabihf__lightningcss-linux-arm-gnueabihf-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-linux-arm-gnueabihf__lightningcss-linux-arm-gnueabihf-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.32.0.tgz"
echo "Downloading lightningcss-linux-arm64-gnu__lightningcss-linux-arm64-gnu-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-linux-arm64-gnu__lightningcss-linux-arm64-gnu-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.32.0.tgz"
echo "Downloading lightningcss-linux-arm64-musl__lightningcss-linux-arm64-musl-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-linux-arm64-musl__lightningcss-linux-arm64-musl-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.32.0.tgz"
echo "Downloading lightningcss-linux-x64-gnu__lightningcss-linux-x64-gnu-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-linux-x64-gnu__lightningcss-linux-x64-gnu-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.32.0.tgz"
echo "Downloading lightningcss-linux-x64-musl__lightningcss-linux-x64-musl-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-linux-x64-musl__lightningcss-linux-x64-musl-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.32.0.tgz"
echo "Downloading lightningcss-win32-arm64-msvc__lightningcss-win32-arm64-msvc-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-win32-arm64-msvc__lightningcss-win32-arm64-msvc-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.32.0.tgz"
echo "Downloading lightningcss-win32-x64-msvc__lightningcss-win32-x64-msvc-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss-win32-x64-msvc__lightningcss-win32-x64-msvc-1.32.0.tgz" "https://registry.npmjs.org/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.32.0.tgz"
echo "Downloading lightningcss__lightningcss-1.32.0.tgz..."
curl -sL -o "$DEST/lightningcss__lightningcss-1.32.0.tgz" "https://registry.npmjs.org/lightningcss/-/lightningcss-1.32.0.tgz"
echo "Downloading loose-envify__loose-envify-1.4.0.tgz..."
curl -sL -o "$DEST/loose-envify__loose-envify-1.4.0.tgz" "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz"
echo "Downloading lucide-react__lucide-react-1.7.0.tgz..."
curl -sL -o "$DEST/lucide-react__lucide-react-1.7.0.tgz" "https://registry.npmjs.org/lucide-react/-/lucide-react-1.7.0.tgz"
echo "Downloading maath__maath-0.10.8.tgz..."
curl -sL -o "$DEST/maath__maath-0.10.8.tgz" "https://registry.npmjs.org/maath/-/maath-0.10.8.tgz"
echo "Downloading magic-string__magic-string-0.30.21.tgz..."
curl -sL -o "$DEST/magic-string__magic-string-0.30.21.tgz" "https://registry.npmjs.org/magic-string/-/magic-string-0.30.21.tgz"
echo "Downloading meshline__meshline-3.3.1.tgz..."
curl -sL -o "$DEST/meshline__meshline-3.3.1.tgz" "https://registry.npmjs.org/meshline/-/meshline-3.3.1.tgz"
echo "Downloading meshoptimizer__meshoptimizer-1.0.1.tgz..."
curl -sL -o "$DEST/meshoptimizer__meshoptimizer-1.0.1.tgz" "https://registry.npmjs.org/meshoptimizer/-/meshoptimizer-1.0.1.tgz"
echo "Downloading nanoid__nanoid-3.3.11.tgz..."
curl -sL -o "$DEST/nanoid__nanoid-3.3.11.tgz" "https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz"
echo "Downloading path-key__path-key-3.1.1.tgz..."
curl -sL -o "$DEST/path-key__path-key-3.1.1.tgz" "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz"
echo "Downloading picocolors__picocolors-1.1.1.tgz..."
curl -sL -o "$DEST/picocolors__picocolors-1.1.1.tgz" "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz"
echo "Downloading picomatch__picomatch-4.0.4.tgz..."
curl -sL -o "$DEST/picomatch__picomatch-4.0.4.tgz" "https://registry.npmjs.org/picomatch/-/picomatch-4.0.4.tgz"
echo "Downloading postcss__postcss-8.5.8.tgz..."
curl -sL -o "$DEST/postcss__postcss-8.5.8.tgz" "https://registry.npmjs.org/postcss/-/postcss-8.5.8.tgz"
echo "Downloading potpack__potpack-1.0.2.tgz..."
curl -sL -o "$DEST/potpack__potpack-1.0.2.tgz" "https://registry.npmjs.org/potpack/-/potpack-1.0.2.tgz"
echo "Downloading promise-worker-transferable__promise-worker-transferable-1.0.4.tgz..."
curl -sL -o "$DEST/promise-worker-transferable__promise-worker-transferable-1.0.4.tgz" "https://registry.npmjs.org/promise-worker-transferable/-/promise-worker-transferable-1.0.4.tgz"
echo "Downloading react-dom__react-dom-18.3.1.tgz..."
curl -sL -o "$DEST/react-dom__react-dom-18.3.1.tgz" "https://registry.npmjs.org/react-dom/-/react-dom-18.3.1.tgz"
echo "Downloading react-use-measure__react-use-measure-2.1.7.tgz..."
curl -sL -o "$DEST/react-use-measure__react-use-measure-2.1.7.tgz" "https://registry.npmjs.org/react-use-measure/-/react-use-measure-2.1.7.tgz"
echo "Downloading react__react-18.3.1.tgz..."
curl -sL -o "$DEST/react__react-18.3.1.tgz" "https://registry.npmjs.org/react/-/react-18.3.1.tgz"
echo "Downloading require-from-string__require-from-string-2.0.2.tgz..."
curl -sL -o "$DEST/require-from-string__require-from-string-2.0.2.tgz" "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz"
echo "Downloading rolldown__rolldown-1.0.0-rc.12.tgz..."
curl -sL -o "$DEST/rolldown__rolldown-1.0.0-rc.12.tgz" "https://registry.npmjs.org/rolldown/-/rolldown-1.0.0-rc.12.tgz"
echo "Downloading scheduler__scheduler-0.23.2.tgz..."
curl -sL -o "$DEST/scheduler__scheduler-0.23.2.tgz" "https://registry.npmjs.org/scheduler/-/scheduler-0.23.2.tgz"
echo "Downloading scheduler__scheduler-0.27.0.tgz..."
curl -sL -o "$DEST/scheduler__scheduler-0.27.0.tgz" "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz"
echo "Downloading shebang-command__shebang-command-2.0.0.tgz..."
curl -sL -o "$DEST/shebang-command__shebang-command-2.0.0.tgz" "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz"
echo "Downloading shebang-regex__shebang-regex-3.0.0.tgz..."
curl -sL -o "$DEST/shebang-regex__shebang-regex-3.0.0.tgz" "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz"
echo "Downloading source-map-js__source-map-js-1.2.1.tgz..."
curl -sL -o "$DEST/source-map-js__source-map-js-1.2.1.tgz" "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz"
echo "Downloading stats-gl__stats-gl-2.4.2.tgz..."
curl -sL -o "$DEST/stats-gl__stats-gl-2.4.2.tgz" "https://registry.npmjs.org/stats-gl/-/stats-gl-2.4.2.tgz"
echo "Downloading stats.js__stats.js-0.17.0.tgz..."
curl -sL -o "$DEST/stats.js__stats.js-0.17.0.tgz" "https://registry.npmjs.org/stats.js/-/stats.js-0.17.0.tgz"
echo "Downloading suspend-react__suspend-react-0.1.3.tgz..."
curl -sL -o "$DEST/suspend-react__suspend-react-0.1.3.tgz" "https://registry.npmjs.org/suspend-react/-/suspend-react-0.1.3.tgz"
echo "Downloading tailwindcss__tailwindcss-4.2.2.tgz..."
curl -sL -o "$DEST/tailwindcss__tailwindcss-4.2.2.tgz" "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.2.2.tgz"
echo "Downloading tapable__tapable-2.3.2.tgz..."
curl -sL -o "$DEST/tapable__tapable-2.3.2.tgz" "https://registry.npmjs.org/tapable/-/tapable-2.3.2.tgz"
echo "Downloading three-mesh-bvh__three-mesh-bvh-0.8.3.tgz..."
curl -sL -o "$DEST/three-mesh-bvh__three-mesh-bvh-0.8.3.tgz" "https://registry.npmjs.org/three-mesh-bvh/-/three-mesh-bvh-0.8.3.tgz"
echo "Downloading three-stdlib__three-stdlib-2.36.1.tgz..."
curl -sL -o "$DEST/three-stdlib__three-stdlib-2.36.1.tgz" "https://registry.npmjs.org/three-stdlib/-/three-stdlib-2.36.1.tgz"
echo "Downloading three__three-0.170.0.tgz..."
curl -sL -o "$DEST/three__three-0.170.0.tgz" "https://registry.npmjs.org/three/-/three-0.170.0.tgz"
echo "Downloading three__three-0.183.2.tgz..."
curl -sL -o "$DEST/three__three-0.183.2.tgz" "https://registry.npmjs.org/three/-/three-0.183.2.tgz"
echo "Downloading tinyglobby__tinyglobby-0.2.15.tgz..."
curl -sL -o "$DEST/tinyglobby__tinyglobby-0.2.15.tgz" "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.15.tgz"
echo "Downloading troika-three-text__troika-three-text-0.52.4.tgz..."
curl -sL -o "$DEST/troika-three-text__troika-three-text-0.52.4.tgz" "https://registry.npmjs.org/troika-three-text/-/troika-three-text-0.52.4.tgz"
echo "Downloading troika-three-utils__troika-three-utils-0.52.4.tgz..."
curl -sL -o "$DEST/troika-three-utils__troika-three-utils-0.52.4.tgz" "https://registry.npmjs.org/troika-three-utils/-/troika-three-utils-0.52.4.tgz"
echo "Downloading troika-worker-utils__troika-worker-utils-0.52.0.tgz..."
curl -sL -o "$DEST/troika-worker-utils__troika-worker-utils-0.52.0.tgz" "https://registry.npmjs.org/troika-worker-utils/-/troika-worker-utils-0.52.0.tgz"
echo "Downloading tslib__tslib-2.8.1.tgz..."
curl -sL -o "$DEST/tslib__tslib-2.8.1.tgz" "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz"
echo "Downloading tunnel-rat__tunnel-rat-0.1.2.tgz..."
curl -sL -o "$DEST/tunnel-rat__tunnel-rat-0.1.2.tgz" "https://registry.npmjs.org/tunnel-rat/-/tunnel-rat-0.1.2.tgz"
echo "Downloading use-sync-external-store__use-sync-external-store-1.6.0.tgz..."
curl -sL -o "$DEST/use-sync-external-store__use-sync-external-store-1.6.0.tgz" "https://registry.npmjs.org/use-sync-external-store/-/use-sync-external-store-1.6.0.tgz"
echo "Downloading utility-types__utility-types-3.11.0.tgz..."
curl -sL -o "$DEST/utility-types__utility-types-3.11.0.tgz" "https://registry.npmjs.org/utility-types/-/utility-types-3.11.0.tgz"
echo "Downloading vite__vite-8.0.3.tgz..."
curl -sL -o "$DEST/vite__vite-8.0.3.tgz" "https://registry.npmjs.org/vite/-/vite-8.0.3.tgz"
echo "Downloading webgl-constants__webgl-constants-1.1.1.tgz..."
curl -sL -o "$DEST/webgl-constants__webgl-constants-1.1.1.tgz" "https://registry.npmjs.org/webgl-constants/-/webgl-constants-1.1.1.tgz"
echo "Downloading webgl-sdf-generator__webgl-sdf-generator-1.1.1.tgz..."
curl -sL -o "$DEST/webgl-sdf-generator__webgl-sdf-generator-1.1.1.tgz" "https://registry.npmjs.org/webgl-sdf-generator/-/webgl-sdf-generator-1.1.1.tgz"
echo "Downloading which__which-2.0.2.tgz..."
curl -sL -o "$DEST/which__which-2.0.2.tgz" "https://registry.npmjs.org/which/-/which-2.0.2.tgz"
echo "Downloading zustand__zustand-4.5.7.tgz..."
curl -sL -o "$DEST/zustand__zustand-4.5.7.tgz" "https://registry.npmjs.org/zustand/-/zustand-4.5.7.tgz"
echo "Downloading zustand__zustand-5.0.12.tgz..."
curl -sL -o "$DEST/zustand__zustand-5.0.12.tgz" "https://registry.npmjs.org/zustand/-/zustand-5.0.12.tgz"

echo ""
echo "Done! Downloaded 156 packages to $DEST/"
